name: Bug Report
description: Report a bug in the application
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        **Describe the bug**
        A clear and concise description of what the bug is.
  - type: input
    attributes:
      label: What is the expected behavior?
      description: Describe what you expected to happen.
      placeholder: Expected behavior...
  - type: input
    attributes:
      label: What are the steps to reproduce?
      description: List the steps to reproduce the issue.
      placeholder: Steps to reproduce...
  - type: input
    attributes:
      label: What did you see instead?
      description: Describe what you observed instead of the expected behavior.
      placeholder: Observed behavior...
  - type: input
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Additional context...
